points:
  key:
    padding: cy
    tags:
      1u: true
    footprints:
      choc_hotswap:
        type: choc
        nets:
          from: =column_net
          to: GND
        params:
          keycaps: true
          reverse: true
          hotswap: true
  zones:
    main:
      rows:
        bottom:
        home:
        top:
      columns:
        pinkie:
          spread: cx
          rows:
            bottom:
              bind: [0,1,0,1]
              column_net: P1
            home:
              bind: [0,1,0,1]
              column_net: P0
            top:
              bind: [1,1,0,1]
              column_net: P2
        ring:
          spread: cx
          stagger: 6
          rows:
            bottom:
              bind: [0,1,4,0]
              column_net: P21
            home:
              bind: [0,1,0,0]
              column_net: P3
            top:
              bind: [1,1,0,1]
              column_net: P20
        middle:
          spread: cx
          stagger: 4
          rows:
            bottom:
              bind: [0,0,5,0]
              column_net: P4
            home:
              bind: [0,0,0,0]
              column_net: P19
            top:
              bind: [1,1,0,1]
              column_net: P5
        index:
          spread: cx
          stagger: -3
          rows:
            bottom:
              bind: [0,0,4,1]
              column_net: P18
            home:
              bind: [0,0,0,1]
              column_net: P6
            top:
              bind: [1,1,0,1]
              column_net: P15
        indexouter:
          spread: cx
          stagger: -2
          rows:
            bottom:
              bind: [0,1,4,1]
              column_net: P7
            home:
              bind: [0,1,0,1]
              column_net: P14
            top:
              bind: [1,1,0,1]
              column_net: P8
    thumb:
      anchor:
        ref: main_indexouter_bottom
        shift: [-13,-20]
      rows:
      columns:
        inner:
          rows:
            home:
              bind: [5,5,0,5]
              column_net: P10
              tags:
                1u: false
                15u: true
        outer:
          rotate: 90
          spread: cx+4
          stagger: -5
          rows:
            home:
              bind: [0,5,0,5]
              column_net: P9
              tags:
                1u: false
                15u: true
outlines:
  exports:
    raw: 
      - type: keys
        side: left
        size: [1cx - 0.5 , 1cx -0.5]
      - type: rectangle
        size: [55, 40]
        anchor:
          ref: main_indexouter_bottom
          rotate: 0
          shift: [-81.75, -34]
      - type: rectangle
        size: [10, 5]
        anchor:
          ref: main_pinkie_top
          rotate: 0
          shift: [0, 3.75]
      - type: rectangle
        size: [10, 5]
        anchor:
          ref: main_ring_top
          rotate: 0
          shift: [0, 3.75]
      - type: rectangle
        size: [10, 5]
        anchor:
          ref: main_middle_top
          rotate: 0
          shift: [0, .75]
      - type: rectangle
        size: [10, 5]
        anchor:
          ref: main_index_top
          rotate: 0
          shift: [0, 1.75]
    cutout:
      - type: outline
        name: raw
        fillet: .75
    keycap_outlines:
      - type: keys
        side: left
        size: [1cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false    
        tags: [1u]       
    keycap_outlines15:
      - type: keys
        side: left
        size: [1.5cx - 0.5, 1cy - 0.5] # Choc keycaps are 17.5 x 16.5
        bound: false    
        tags: [15u]       
    preview:
        [keycap_outlines,keycap_outlines15]
pcbs:
  gentle34:
    outlines:
      board:
        outline: cutout
      keycaps:
        outline: preview
        layer: Eco1.User
    footprints:
      promicro:
        type: promicro_pretty
        anchor:
          ref: main_pinkie_bottom
          shift: [9.5, -19]
          rotate: 0
      pcm12:
        type: pcm12
        anchor:
          ref: main_pinkie_bottom
          shift: [40.5, -26.5]
        nets:
          from: pos
          to: RAW
        params:
          reverse: true
      b3u1000p:
        type: b3u1000p
        nets:
          r1: RST
          r2: GND
        anchor:
          ref: main_pinkie_bottom
          shift: [32, -26.25]
          rotate: 0
        params:
          reverse: true
      via1:
        type: via
        anchor: 
          ref: main_pinkie_bottom
          shift: [40.5, -23]
        nets: 
          net: RAW 
      via2:
        type: via
        anchor: 
          ref: main_pinkie_bottom
          shift: [40.5, -21.75]
        nets: 
          net: pos 
      via3:
        type: via
        anchor: 
          ref: main_pinkie_bottom
          shift: [32, -22.75]
        nets: 
          net: GND 
      via4:
        type: via
        anchor: 
          ref: main_pinkie_bottom
          shift: [32, -24]
        nets: 
          net: RST
      jstph:
        type: jstph
        anchor: 
          ref: main_pinkie_bottom
          shift: [31, -19]
          rotate: 90
        nets:
          pos: pos
          neg: GND

