manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-config-gentle34
      url-base: https://github.com/talbotsolenberger
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboards-gentle34
      remote: zmk-config-gentle34
      revision: master
  self:
    path: config
