manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # - name: talbotsolenberger
    #   url-base: https://github.com/talbotsolenberger
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3 # version with working bluetooth
      # revision: main # version for most up to date features
      import: app/west.yml
    # - name: zmk-config-gentle34
    #   remote: talbotsolenberger
    #   revision: master
  self:
    path: config
