manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: gentle34-shield-module
      url-base: https://github.com/talbotsolenberger
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-keyboards-gentle34
      remote: gentle34-shield-module
      revision: master
  self:
    path: config
